# Generated by Django 4.0.4 on 2022-05-31 10:07

import api.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(choices=[(6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')])),
                ('minute', models.IntegerField(choices=[(0, '00'), (30, '30')])),
                ('content', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=1)),
                ('color', models.CharField(default=api.models.Block.randomColor, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator()])),
                ('passwordHash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(default=datetime.date.today, max_length=75)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('scheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
        ),
    ]
